# Generated by Django 3.1.4 on 2020-12-07 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stripe_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="stripe_customer_id",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="payment_method",
            name="stripe_payment_method_id",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=50)),
                ("purchase_date", models.DateField()),
                ("price_id", models.FloatField()),
                ("stripe_subscription_id", models.CharField(max_length=50)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stripe_api.customer",
                    ),
                ),
            ],
        ),
    ]
