# Generated by Django 3.1.4 on 2020-12-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_method',
            name='stripe_payment_method_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
