# Generated by Django 3.1.4 on 2020-12-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stripe_api", "0002_auto_20201207_1711"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="price_id",
            field=models.CharField(max_length=50),
        ),
    ]
