# Generated by Django 3.1.4 on 2020-12-12 14:58

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_api', '0004_customer_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_method',
            name='key',
            field=fernet_fields.fields.EncryptedTextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='key',
            field=fernet_fields.fields.EncryptedTextField(default='null'),
            preserve_default=False,
        ),
    ]
