# Generated by Django 3.1.4 on 2020-12-12 15:00

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_api', '0005_auto_20201212_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', fernet_fields.fields.EncryptedTextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='key',
        ),
        migrations.RemoveField(
            model_name='payment_method',
            name='key',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='key',
        ),
    ]
