name: Python application
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migrations
      run: python stripe_subscription/manage.py migrate
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
    - name: Run tests
      run: python stripe_subscription/manage.py test
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
