name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "stripe-sub" #Must be unique in Heroku
          heroku_email: "subhaac@yahoo.co.uk"
      - name: Run migrations
        run: python manage.py migrate
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
